### ISSUE TITLE
Coordinación de plan de trabajo relacionado a la programación

### ISSUE THREAD

**Issue by AndresVA99** [AzofeifaJ/Diseno_Logico-Proyecto_2#2]
### Descripción 
Se realizó una reunión con todos los miembros del equipo para poder crear por medio de un diagrama de flujo un esquema del plan de trabajo, las responsabilidades para cada tarea y las especificaciones para la programación del multiplicador.

![Image](https://user-images.githubusercontent.com/111375712/231040286-a2a716a7-fee8-4359-a3a4-1a605ab350e3.png)

En dicha reunión se llegó al acuerdo en dividir la programación en 4 submódulos para que cada integrante pueda trabajar en forma simultánea en varias partes del proyecto, se dejó abierta la posibilidad de la participación de otros integrantes del equipo en un submódulo que el encargado requiera soporte. 
Queda en claro que conforme a como se va programando los submódulos podrán surgir a la hora de programar.

**Comment by JoseDavidL** [comment]
![null](https://user-images.githubusercontent.com/111375712/233233088-eb7fb569-ab02-423a-8237-c355e1ff4029.png)
