### ISSUE TITLE
Confección de diagramas de bloques de los modos

### ISSUE THREAD

**Issue by AndresVA99** [AzofeifaJ/Diseno_Logico-Proyecto_2#9]

**Comment by JoseDavidL** [comment]
###  Diagrama de bloques Subsistema de lectura y sincronización.

![image](https://user-images.githubusercontent.com/111375712/236116173-fd49037f-f15e-43b5-9f37-8bf741c5ee3e.png)

**Comment by JoseDavidL** [comment]
###  Diagrama de bloques Subsistema de cálculo de código BCD.

![image](https://user-images.githubusercontent.com/111375712/236116624-66f617c1-c7f3-4f5f-8ddd-a707cb03274c.png)

**Comment by JoseDavidL** [comment]
###  Diagrama de bloques Subsistema de decodificado en display de 7 segmentos. 

![image](https://user-images.githubusercontent.com/111375712/236115926-6a558b75-e8e1-4ec2-8bd5-a5ba27bc673d.png)
